// ISLAND SCALING AND GEOMETRY HELPERS — not a city list.
//
// Every playable island is generated by island.mjs from a seed. This module
// holds the shared helpers the generator and makeCity use: the partition cut
// helper, the size presets, and scaleCity which grows or shrinks an island
// config without breaking block dimensions.
//
// The district plan of a generated island is a BSP tree, so the leaves tile
// the plane and the map cannot have a hole in it. Cuts are written with the
// helper below rather than as raw half-planes, because `cut(0, -330, 0)` — a
// line through (0, -330) running due east — is something a person can picture,
// and `[0, 1, -330]` is not.

// A cut through (px, py) travelling at `deg` (0 = east, 90 = north).
// `neg` is the LEFT-HAND side of that travel; `pos` is the right.
// Exported because island.mjs writes its partitions with it too — a generated
// island's district plan has to be the same kind of object as a hand-drawn
// one's, and that starts with being cut by the same helper.
export const cut = (px, py, deg) => {
  const t = (deg * Math.PI) / 180;
  const nx = Math.sin(t), ny = -Math.cos(t);
  return [nx, ny, px * nx + py * ny];
};

/**
 * HOW BIG THIS TOWN IS — and the one thing that must NOT change with it.
 *
 * A bigger island is more blocks, not bigger blocks. Manhattan's blocks are
 * the same size as a small town's; there are simply a great many more of them.
 * So the scale multiplies every POSITION and every EXTENT in the geography —
 * the coastline, the core radii, the partition cuts, the parks, the piers —
 * and leaves the street grid alone: stPitch, avePitch, streetW, aveW and the
 * organic districts' block-area range are dimensions of a city block, and a
 * block is a block at any city size.
 *
 * Scaling the pitch too would have been the easy version and it would have
 * been wrong twice over. Visually it is a zoom, not a bigger town — the same
 * map with everything fattened. Economically it is worse: lot areas, buildable
 * envelopes, rent per square foot and cost per square foot are all quoted
 * against real dimensions, so a 2x grid would hand every parcel four times the
 * land under the same building and quietly break every number the economy is
 * measured in.
 *
 * Land area goes as the square of this, so lot count roughly does too: 0.55
 * gives about a third of a standard town, 2.0 about four times one.
 *
 * The core RADII do scale. A core's reach is the decay length of the land
 * gradient, and downtown in a big city genuinely does pull further than
 * downtown in a small one. Keeping them fixed would make a large island almost
 * entirely fringe — one small bright middle and miles of nothing — which is a
 * different city rather than a bigger one.
 */
export const SIZES = {
  hamlet: { k: 0.55, name: "Hamlet", note: "A few hundred lots — same opening cheque, small pond. You can hold every corner, and own a real slice of it." },
  town:   { k: 0.78, name: "Town", note: "Half the standard map. Tight, and every mistake is visible." },
  city:   { k: 1.00, name: "City", note: "The standard island — about fourteen hundred lots, two miles end to end." },
  metro:  { k: 1.45, name: "Metropolis", note: "Twice the land. Same cheque, deeper pond — rivals and bank holds sized up with the map." },
  giant:  { k: 2.00, name: "Great City", note: "Four times the land. Same opening money; you are a minnow. A career is not long enough to learn all of it." },
};
export const DEFAULT_SIZE = "city";

const isNum = (v) => typeof v === "number" && Number.isFinite(v);
const pt = (p, k) => (Array.isArray(p) ? [p[0] * k, p[1] * k] : p);

/** Scale the third term of a half-plane [nx, ny, c]: the normal is a direction, c is a distance. */
function scaleCuts(node, k) {
  if (!node || typeof node !== "object" || !node.cut) return node;
  return {
    ...node,
    cut: [node.cut[0], node.cut[1], node.cut[2] * k],
    pos: scaleCuts(node.pos, k),
    neg: scaleCuts(node.neg, k),
  };
}

/** Positions inside a district config scale; everything else about it does not. */
function scaleDistricts(ds, k) {
  const out = {};
  for (const [name, d] of Object.entries(ds ?? {})) out[name] = d.focus ? { ...d, focus: pt(d.focus, k) } : d;
  return out;
}

export function scaleCity(cfg, k) {
  if (!isNum(k) || Math.abs(k - 1) < 1e-6) return cfg;
  const box = (o) => ({
    ...o,
    cx: o.cx * k, cy: o.cy * k, w: o.w * k, h: o.h * k,
    ...(o.ring ? { ring: o.ring.map((p) => pt(p, k)) } : {}),
  });
  return {
    ...cfg,
    coast: cfg.coast.map((p) => pt(p, k)),
    coastAmp: cfg.coastAmp * k,
    esplanade: cfg.esplanade * k,
    cores: cfg.cores.map((c) => ({ ...c, xy: pt(c.xy, k), r: c.r * k })),
    lighthouse: cfg.lighthouse ? pt(cfg.lighthouse, k) : cfg.lighthouse,
    partition: scaleCuts(cfg.partition, k),
    districts: scaleDistricts(cfg.districts, k),
    parks: (cfg.parks ?? []).map(box),
    diagonals: (cfg.diagonals ?? []).map(box),
    piers: (cfg.piers ?? []).map((ring) => ring.map((p) => pt(p, k))),
    cranes: (cfg.cranes ?? []).map(([x, y, d]) => [x * k, y * k, d]),
    ships: (cfg.ships ?? []).map(([x, y, d]) => [x * k, y * k, d]),
    breakwaters: (cfg.breakwaters ?? []).map(([x, y, w, h, d]) => [x * k, y * k, w * k, h * k, d]),
    stations: (cfg.stations ?? []).map((st) => ({ ...st, xy: pt(st.xy, k) })),
    labels: (cfg.labels ?? []).map((l) => ({ ...l, xy: pt(l.xy, k) })),
  };
}
